### ISSUE TITLE
Instructions aren't quite complete

### ISSUE THREAD

**Issue by JeffAbrahamson** [jcugat/django-custom-user#19]
The instructions in README.rst don't quite cover using django-custom-user.  I think the missing bits are just urls.py and the necessary templates.  The first reaction on not seeing those specified is to use the urls.py and templates from the django default registration backend, but that leads to some odd behavior on user registration, as discussed in this [SO](http://stackoverflow.com/questions/29670953/django-django-custom-user-and-registration-becomes-no-op) question.

**Comment by JeffAbrahamson** [comment]
This is seeming quite intricate, or I'm terribly confused.  Either is possible.

The class RegistrationView in file registration/backends/default/views.py explicitly looks for the username field in the model.  I don't see an easy way to modify that except to copy it or derive and override register().  RegistrationView also calls RegistrationProfile.objects.create_inactive_user() with a user name.  My first stab is to make EmailUserManager.create_user() take a username argument and ignore it, though this is hideously ugly.

The file registration/backends/default/urls.py explicitly references RegistrationView (by path), so it seems to need to be copied and changed.

**Comment by JeffAbrahamson** [comment]
I've forked the repository, hacked together something that does about what I describe above, and pushed it [here](https://github.com/JeffAbrahamson/django-custom-user).

It's really ugly and probably not the right way to do this.  I'm really sorry to introduce such a thing into the world.

**Comment by jcugat** [comment]
Hi Jeff,

In this issue you mention the default django registration backend, but in the StackOverflow question there is a mention to django-registration, a third-party package. This problem is using the latter?

**Comment by JeffAbrahamson** [comment]
Ah, this is a very good question.  Indeed I am using django-registration.  Iirc, in order to have two-phase registration (email confirmation).  So perhaps this is simply a bug in that package.

**Comment by jcugat** [comment]
Yes, it seems that it's no longer mantained (see https://bitbucket.org/ubernostrum/django-registration/pull-request/63/django-16-compatibility-fix-auth-views/diff#comment-1646840) and I think the problem is it's not compatible with custom user models, introduced in django 1.5.

**Comment by JeffAbrahamson** [comment]
That confusion seems very likely to be the cause of my problems.  The code looks custom user model clean.  I'll follow on in a  bit for the record (for future searchers), both here and on SO.  Thanks!

**Comment by jcugat** [comment]
No problem :)

**Comment by JeffAbrahamson** [comment]
Quick follow on for future readers of this (closed) issue:

The name to use in a requirements.txt file is django-registration-redux.
The thing that is installed appears to be django-registration.  In any case, it's in the directory registration/.
I suspect a story about compatibility with something.
