### ISSUE TITLE
MySQL error on migration: (1071, 'Specified key was too long; max key length is 767 bytes')

### ISSUE THREAD

**Issue by ilhan** [jcugat/django-custom-user#31]
When using utfmb4 as you should 😃 a default MySQL installation errors out.

[~~This pull request~~](https://github.com/jcugat/django-custom-user/pull/30) lowers the max_length to 150 from 255.
Another approach could be to write a warning to utfmb4 users somewhere if you dont want to limit those not affected.

**Comment by ilhan** [comment]
Hm, dont experience the same problem on MySQL 5.7.11 via homebrew on Mac.
Had the problem on MySQL 5.5.44 via apt-get on Debian.

**Comment by ilhan** [comment]
This is [fixed by default](http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix) in MySQL 5.7.7
[Guide for older MySQL](http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/)

**Comment by jcugat** [comment]
This was also discussed in https://github.com/jcugat/django-custom-user/pull/29

Thanks for the extra info about old MySQL versions!
