### ISSUE TITLE
Change password link in EmailUserChangeForm does not work since Django 1.9

### ISSUE THREAD

**Issue by rubengrill** [jcugat/django-custom-user#36]
- Urls changed in 1.9: https://github.com/django/django/commit/1791a7e75af8c9e7ca54425592379fd1f840fe88
- Change password link was changed in UserChangeForm: https://github.com/django/django/commit/c2bfd76ec3678cc28fb6fce6be0ae217b46bcd9e
- Reverse url can't be used, as the url name does also exist since then: https://github.com/django/django/commit/32e6a7d3a57b2287d55e8b8efa4e8cb7643b1720

PR will follow.

**Comment by alamasfu10** [comment]
HI @jcugat when are you planning to release a new version of `django-custom-user` that contains this fix?

**Comment by jcugat** [comment]
Completely forgot about it. I have uploaded version 0.7 with the link fix.
