### ISSUE TITLE
"Change password" admin page is missing

### ISSUE THREAD

**Issue by joeyespo** [jcugat/django-custom-user#39]
When you visit a `User` admin page, Django provides a link to set someone's password

![change password form link](https://cloud.githubusercontent.com/assets/634573/21994745/51b7f264-dbef-11e6-91c9-2abe2aa9b4c8.png)

When clicking that link with Django Custom User installed, it 404's

![change password form 404](https://cloud.githubusercontent.com/assets/634573/21994871/ddb715f6-dbef-11e6-8b60-7fa30f3c2b60.png)

From the error, `user object with primary key u'1/change' does not exist`, looks like either a URL regex might be outdated, or this functionality was never implemented in the first place.

**Comment by jcugat** [comment]
It seems to work in my end with Django 1.10

<img width="1107" alt="screen shot 2017-01-19 at 16 27 02" src="https://cloud.githubusercontent.com/assets/488594/22112684/2626cff4-de64-11e6-92d6-2058f8d270e7.png">

Can you give more info, for example which version of Django and `django-custom-user` are you using?

**Comment by joeyespo** [comment]
Oh, interesting!

I'm also using Django 1.10, so it's like a mistake on my end. I'll try some things locally and then comment back here.

**Comment by joeyespo** [comment]
Ah yep, looks like I just needed to upgrade to 0.7. [Looks like this fixed the problem](https://github.com/jcugat/django-custom-user/commit/3e9e12af3c0224ad16e95279af1dd37b6bdab0db).

Thanks!

**Comment by jcugat** [comment]
No problem, thanks for confirming it :)

**Comment by rickbrunstedt** [comment]
Sorry if offtopic, but I don't wanna do a new issue about this, because it's probably something that I have done wrong. :/ (django noob) 
That link you are showing on the image doesn't even show in the admin for me.. all I got is a hashed password in a regular input field.

What am I missing here? Is it something I have to add afterwards?

**Comment by jcugat** [comment]
How are you using `EmailUser`, directly or subclassing it? Which version of Django are you running?

**Comment by rickbrunstedt** [comment]
It works fine now. I'm did the same thing as the person in #13 . But thanks!
