### ISSUE TITLE
Deprecation warning for ugettext_lazy

### ISSUE THREAD

**Issue by pinghedm** [jcugat/django-custom-user#51]
Have been using this library since Django 1.6, works really well, no complaints - thanks for building!

In at least Django 2, `ugettext_lazy` issues a deprecation warning in favor if `gettext_lazy` - related to deprecating Python 2 support, I assume

Is there interest in releasing a new version of this, changing imports of `ugettext_lazy` to `gettext_lazy`?  Otherwise should be no changes needed, `ugettext_lazy` is just an alias for `gettext_lazy` as it is.  

I'm happy to make a PR (basically trivial) - but if there isn't interest in a version bump after so long I understand, and we'll probably move to vendoring our own version

**Comment by mjtamlyn** [comment]
This module is now broken on Django 4.0 due to this issue

**Comment by jcugat** [comment]
@pinghedm  @mjtamlyn a new version has been released which fixes this! It's now compatible with Django v4.0.
